openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://api.server.test/v1

tags:
  - name: s3
    description: About s3

paths:
  /{bucketname}/{objectkey}:
    parameters:
      - name: bucketname
        in: path
        description: s3 bucket name
        required: true
        schema:
          type: string
      - name: key
        in: path
        description: s3 object key
        required: true
        schema:
          type: string
    get:
      tags:
        - s3
      summary: get s3 object
      responses:
        "200":
          description: OK
          # content:
          #   audio/mpeg:
          #     schema:
          #       $ref: "#/components/schemas/Analysis"
          headers:
            Content-Length:
              type: string
            Content-Type:
              type: string

  /presigned_url:
    post:
      summary: s3から取得するためのpresigned_urlの生成
      tags:
        - s3
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pdf_id:
                  type: string
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  source:
                    type: string
                  presigned_url:
                    type: string

  /presigned_post:
    post:
      summary: アップロード用署名urlの生成
      tags:
        - s3
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                  headers:
                    type: object
                    properties:
                      key:
                        type: string
                      AWSAccessKeyId:
                        type: string
                      policy:
                        type: string
                      signature:
                        type: string

components:
  schemas:
    Analyses:
      type: array
      required:
        - id
      items:
        $ref: "#/components/schemas/Analysis"
    Analysis:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        pdf_id:
          type: string
        data:
          type: object
          properties:
            segments:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  value:
                    type: string
                  position:
                    type: string
        status:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
