AWSTemplateFormatVersion: 2010-09-09
Description: CloudTrail
Parameters:
  BucketName:
    Type: String
    Default: AccountAlias-cloudtrail
    Description: A name for the log bucket.
  TrailName:
    Type: String
    Default: AccountAlias-audit
    Description: A name for cloudtrail.

Resources:
  CloudTrailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      LifecycleConfiguration:
        Rules:
          - Id: 12months(365days)
            Status: Enabled
            ExpirationInDays: 365
    DeletionPolicy: Retain
  CloudTrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudTrailBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action:
              - "s3:GetBucketAcl"
            Resource: !Sub "arn:aws:s3:::${CloudTrailBucket}"
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action:
              - "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${CloudTrailBucket}/AWSLogs/${AWS::AccountId}/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
  CloudTrail:
    DependsOn:
      - CloudTrailBucketPolicy
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName: !Ref CloudTrailBucket
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: true
      EnableLogFileValidation: true
      TrailName: !Ref TrailName
