---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for auto stop and start RDS
#
# Metadata
#
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: CloudWatch Events Configuration
      Parameters:
      - StartSchedule
      - StopSchedule
#
# Parameters
#
Parameters:
  StartSchedule:
    Description: Start Datetime format cron
    Default: 0 23 ? * SUN-THU *
    Type: String
  StopSchedule:
    Description: Stop Datetime format cron
    Default: 0 10 ? * MON-FRI *
    Type: String
#
# Resources
#
Resources:
  StateSchedulerExecRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: rds-sheduler-lambda-role
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: LambdaExecPolicy
        PolicyDocument:
          Statement:
          - Sid: AccessToCWLog
            Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"
          - Sid: AccessToRDS
            Effect: Allow
            Action:
            - rds:StopDBInstance
            - rds:StartDBInstance
            - rds:DescribeDBInstances
            - rds:ListTagsForResource
            Resource: "*"
  StateSchedulerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import boto3
          def lambda_handler(event, context):
            RDS = boto3.client('rds')

            instances = RDS.describe_db_instances()

            start_list = []
            stop_list = []
            action = event['Action']

            for i in instances['DBInstances']:
              tags = RDS.list_tags_for_resource(ResourceName=i['DBInstanceArn'])['TagList']
              if tags != None:
                for t in tags:
                  if t['Key'] == 'RDSStartStop':
                    if t['Value'] == 'Auto' or t['Value'] == action:
                      if action == 'Start' and i['DBInstanceStatus'] == 'stopped':
                        start_list.append(i['DBInstanceIdentifier'])
                      elif action == 'Stop' and i['DBInstanceStatus'] == 'available':
                        stop_list.append(i['DBInstanceIdentifier'])

            for s in start_list:
              RDS.start_db_instance(DBInstanceIdentifier=s)
              print('Starting', len(s), 'instances', s)
            for s in stop_list:
              RDS.stop_db_instance(DBInstanceIdentifier=s)    
              print('Stopping', len(s), 'instances', s)
      FunctionName: rds-schedule-function
      Description: Scheduled RDS stop and start.
      Handler: index.lambda_handler
      MemorySize: 128
      Role: !GetAtt [ StateSchedulerExecRole, Arn ]
      Runtime: python3.6
      Timeout: 60
  StartScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: ScheduledRule for start instance
      Name: rds-start-rule
      ScheduleExpression: !Sub cron(${StartSchedule})
      State: ENABLED
      Targets:
      - Arn: !GetAtt [ StateSchedulerFunction, Arn ]
        Id: StateSchedulerFunction
        Input: '{"Action":"Start"}'
  StopScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: ScheduledRule for stop instance
      Name: rds-stop-rule
      ScheduleExpression: !Sub cron(${StopSchedule})
      State: ENABLED
      Targets:
      - Arn: !GetAtt [ StateSchedulerFunction, Arn ]
        Id: StateSchedulerFunction
        Input: '{"Action":"Stop"}'
  PermissionForStartEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StateSchedulerFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt [ StartScheduledRule, Arn ]
  PermissionForStopEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StateSchedulerFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt [ StopScheduledRule, Arn ]