version: '3'
services:
  minio:
      image: minio/minio
      entrypoint: sh
      command: -c 'mkdir -p /export/bucket && /usr/bin/minio server /export'
      environment:
        MINIO_ACCESS_KEY: minio_access
        MINIO_SECRET_KEY: minio_secret
      ports:
        - 9000:9000
  app:
    restart: always
    build: 
      context: ./function
      dockerfile: ./Dockerfile
    container_name: app
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - "./function:/app"
    environment:
      TZ: 'Asia/Tokyo'
      AWS_ACCESS_KEY_ID: minio_access
      AWS_SECRET_ACCESS_KEY: minio_secret
      BUCKET_NAME: bucket
      S3_REGION: ap-northeast-1
      AWS_S3_ENDPOINT_URL: 'http://localhost:9000'